channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scikit-image
  - scipy
  - bqplot
  - pythreejs
  - ipyvolume
  - gdal
  - krb5
  - ipyleaflet
  - ipysheet
  - ipytree
  - ipyevents
  - voila
  - pip:
    - ipyvuetify
    - voila-vuetify
    - netcdf4
